language: rust

os:
  - linux
  - osx

rust:
  - stable
  - nightly

before_install:
  - set -e
  - export RUSTFLAGS="-D warnings"
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    rustup self update &&
    rustup component add rustfmt clippy;
    fi

addons:
  chrome: stable

script:
  - if [ "$TRAVIS_RUST_VERSION" != "nightly"]; then
    cargo fmt --all -- --check &&
    cargo clippy --tests;
    fi
  - env RUST_BACKTRACE=1 RUST_LOG=headless_chrome=trace cargo test -- --nocapture
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    cargo test --doc --features nightly;
    fi
