[package]
name = "headless_chrome"
version = "0.3.0"
authors = ["Alistair Roche <alistair@sunburnt.country>"]
edition = "2018"
description = "Control Chrome programatically"
license = "MIT"
homepage = "https://github.com/atroche/rust-headless-chrome"
repository = "https://github.com/atroche/rust-headless-chrome"
readme = "README.md"

[dependencies]
websocket = { version = "0.22", default_features = false, features = ["sync"] }
regex = "1"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
serde_derive = "1"
failure = { version = "0.1", default_features = false, features = ["std"] }
log = "0.4"
env_logger = "0.6"
rand = "0.7"
tempfile = "3"
base64 = "0.10"
derive_builder = "0.7.1"
which = "2.0"
ureq = { version = "0.11", optional = true }
directories = { version = "2.0", optional = true }
zip = { version = "0.5", optional = true }

devtools_proto = { version = "0.3", path = "devtools-proto" }

[target.'cfg(windows)'.dependencies]
winreg = "0.6"

[dev-dependencies]
chrono = { version = "0.4", default_features = false }
tiny_http = "0.6"
png = { version = "0.14" }
jpeg-decoder = { version = "0.1", default_features = false }

[lib]
name = "headless_chrome"
path = "src/lib.rs"

[features]
default = [ "fetch" ]
fetch = [ "ureq", "directories", "zip" ]
nightly = []

[workspace]
members = ["devtools-proto"]
